title = "RAYNET - Deal 10K Jul 27th 2025"
slug = "2025-10-25-raynet-deal-10k-jul-27th-2025"
date = 2025-10-25

summary="Hot day, good marshalls"
tags = ["raynet"]

content = """
The Deal 10K was good. I was posted at Cobham Church, which has
a collection of brass artifacts, and relocated to the back of the
church after all the runners had gone past. Signal was good on
both locations. At some point we got to hear a warning about a "llama
on the road" - apparently the animal had escaped from a farm and
was presumably trying to join the marathon.

Unlike my first event, the runners were coming around a turn so my
binoculars were useless. The marshalls were excellent. It was a Hot
day so I got to hand out more water bottles than I had to press the
radio PTT.

The event was a success.

<div id="map"></div>

<script>
const pos = [51.38993213063418, 0.3983621314289048]
var map = L.map('map').setView(pos, 16);
L.tileLayer('http://sgx.geodatenzentrum.de/wmts_topplus_open/tile/1.0.0/web_grau/default/WEBMERCATOR/{z}/{y}/{x}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
}).addTo(map);
L.marker(pos).addTo(map);
</script>
"""
